export const THEMES = {
  DARK: 'DARK',
  LIGHT: 'LIGHT'
} as const;

export const DIALOG_IDS = {
  BOARD_DIALOG: 'BOARD_DIALOG',
  TASK_DIALOG: 'TASK_DIALOG',
  VIEW_TASK_DIALOG: 'VIEW_TASK_DIALOG',
  DELETE_TASK_DIALOG: 'DELETE_TASK_DIALOG',
  DELETE_BOARD_DIALOG: 'DELETE_BOARD_DIALOG',
  PROFILE_DIALOG: 'PROFILE_DIALOG'
} as const;
