-- AlterTable
ALTER TABLE `board` MODIFY `userId` VARCHAR(191) NOT NULL DEFAULT 'user_2SUAX8aQxluXw745QLofW94VBkT';

-- AlterTable
ALTER TABLE `column` MODIFY `userId` VARCHAR(191) NOT NULL DEFAULT 'user_2SUAX8aQxluXw745QLofW94VBkT';

-- AlterTable
ALTER TABLE `subtask` MODIFY `userId` VARCHAR(191) NOT NULL DEFAULT 'user_2SUAX8aQxluXw745QLofW94VBkT';

-- AlterTable
ALTER TABLE `task` MODIFY `userId` VARCHAR(191) NOT NULL DEFAULT 'user_2SUAX8aQxluXw745QLofW94VBkT';
